# RCA System Configuration

database:
  host: "localhost"
  port: 5432
  name: "rca_system"
  user: "postgres"
  password: "your_password"
  
vector_db:
  collection_name: "rca_patterns"
  persist_directory: "./chroma_db"
  
llm:
  provider: "openai"  # or "llamacpp" for local LLaMA
  model: "gpt-4"
  api_key: "${OPENAI_API_KEY}"
  temperature: 0.1
  max_tokens: 2000
  
rca:
  confidence_threshold: 95
  max_context_length: 4000
  enable_agentic_fallback: true
  
enrichment:
  correlation_window_minutes: 15
  anomaly_threshold: 2.0
  
fusion:
  temporal_weight: 0.4
  semantic_weight: 0.3
  causal_weight: 0.3
  
streamlit:
  host: "0.0.0.0"
  port: 8501
  
logging:
  level: "INFO"
  format: "json"
